refactor: duplication
mkobayashime/manaba-enhanced pull request #488
Opened 2022-11-18 08:36 UTC by yudukikun5120

2022-11-18 08:49 UTC, yudukikun5120 commented on src/methods/filterCourses.ts
@mkobayashime I think the last return expression is useless, but TSC says coursesContainer can be null. Why does it happen?

2022-11-18 08:53 UTC, yudukikun5120 commented on src/methods/filterCourses.ts
@mkobayashime I got the answer. Thank you.

2022-11-18 08:55 UTC, yudukikun5120 commented
@mkobayashime Could you review this PR?

2022-11-26 07:20 UTC, mkobayashime commented on src/methods/filterCourses.ts
> +  ]
```suggestion
  const coursesListContainer =
    document.querySelector<HTMLElement>(".courselist tbody")
  const coursesThumbnailContainer = document.querySelector<HTMLElement>(
    ".mycourses-body .section"
  )
```

I don't see any positive reason for using destructuring assignments here. Do you hava some?

2022-11-26 07:37 UTC, mkobayashime requested changes
Thanks for the work!

2022-11-26 07:37 UTC, mkobayashime commented on src/methods/filterCourses.ts
> +  coursesContainer: HTMLTableElement | HTMLElement,
```suggestion
  coursesContainer: HTMLElement,
```

2022-11-26 07:37 UTC, mkobayashime commented on src/methods/filterCourses.ts
> +    ) as HTMLElement[]
```suggestion
  (Array.from(coursesContainer.children) as HTMLElement[]).filter(
    (_, i) =>
      i !==
      rowIndexToBeExcluded(viewMode, coursesContainer.childElementCount - 1)
  )
```

2022-11-26 11:48 UTC, mkobayashime commented
@yudukikun5120 
Could you run Prettier and squash commits into one?

2022-11-26 12:40 UTC, yudukikun5120 commented
@mkobayashime May I squash the commits when merged?

2022-11-26 12:41 UTC, mkobayashime commented
@yudukikun5120 
Sorry for the confusion. I'd like you to squash these 5 (previously 4) commits into 1 commit, not the merge with squash.

2022-11-26 12:44 UTC, mkobayashime approved these changes
Thanks!

2022-11-26 12:44 UTC, merged

2022-11-26 12:47 UTC, yudukikun5120 commented
@mkobayashime BTW, what do we have to squash the commits before the PRs merge for? What do squashing before the merges and "squash and merge" differ?

2022-11-26 13:11 UTC, mkobayashime commented
@yudukikun5120 
Sorry, I actually confused _Squash and merge_ with _Rebase and merge_. I'll welcome _Squash and merge_ from next time, as long as:
- commits can be bundled into 1 commit semantically (don't have multiple intention)
- commit message is properly set for the new (squashed) commit